Feature/Signup form
hauptrolle/chakra-templates pull request #138
Opened 2021-11-14 12:46 UTC by pranshudobhal

Added a signup form in authentication components

![image](https://user-images.githubusercontent.com/26481473/141681557-b0f15222-b5f1-4f11-b1da-c89683e826df.png)

2021-11-15 20:44 UTC, hauptrolle requested changes
Hey @pranshudobhal!

Thank you so much for your PR. It looks really good!
But can you please remove the `yarn.lock` file from this commit? Than I would merge it into master :)

2021-11-16 17:14 UTC, pranshudobhal commented
Hey @hauptrolle,

I have made the required changes. Please check now! :)

2021-11-21 09:33 UTC, hauptrolle approved these changes

2021-11-21 09:33 UTC, merged

2021-11-21 09:33 UTC, hauptrolle commented
@all-contributors please add @pranshudobhal for code