Multi Step Form Added
hauptrolle/chakra-templates pull request #188
Opened 2022-07-01 10:49 UTC by Prasanna0908

Multi-Step Form Template Added

2022-07-12 08:06 UTC, ekhiw commented
I think you should create new file in `src/data/templates/` and fill it with you template name and template file name, then import into `src/data/index.tsx` add new children in Forms.

2022-07-13 06:13 UTC, Prasanna0908 commented
Made the required changes.

2022-09-29 08:07 UTC, hauptrolle requested changes
Hi, thanks for the contribution. I have left some comments.

2022-09-29 08:07 UTC, hauptrolle commented on tsconfig.json
> +  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", "src/pages/templates/forms/multi-step/multiStep.tsx"],
This should not be neccessary.

2022-09-29 08:07 UTC, hauptrolle commented on .vscode/settings.json
> +}
Please remove that file

2022-10-02 15:27 UTC, Prasanna0908 commented
Made the required changes. Can you check once @hauptrolle

2022-10-02 15:28 UTC, Prasanna0908 commented on .vscode/settings.json
> +}
Done

2022-10-22 09:07 UTC, hauptrolle commented
@Prasanna0908 We are still getting errors on the build step. Are all the paths correct?

```
Error occurred prerendering page "/forms/multiStep". Read more: https://nextjs.org/docs/messages/prerender-error
--
10:50:30.594 | Error: Cannot find module './forms/multiStep/multistep'
``

2022-10-22 09:45 UTC, hauptrolle commented
Can I fix the filename reference? There should be a capital "S".

2022-10-22 10:07 UTC, Prasanna0908 commented
> Can you fix the filename reference? There should be a capital "S".

Yes, please !

2022-10-22 13:10 UTC, Prasanna0908 commented
@hauptrolle Any update?

2022-10-22 15:43 UTC, hauptrolle commented
> @hauptrolle Any update?

Can you fix this? I can't edit files from your PR.

2022-10-23 07:15 UTC, Prasanna0908 commented
is this the correct path (with a capital S)?
'./forms/multiStep/multiStep'

2022-10-23 07:59 UTC, hauptrolle commented
> is this the correct path (with a capital S)? './forms/multiStep/multiStep'

Lets streamline the overall naming a little bit:

The content of `src/data/templates/multistep.ts` should be:

```
import { SubCategory } from '../types';

export const multistep: SubCategory = {
  name: 'Multi Step Forms',
  id: 'multistep',
  children: [
    {
      name: 'Basic 3 Step Form',
      filename: 'basic3StepForm',
    },

  ],
};
```

`src/pages/templates/forms/multi-step/multiStep.tsx` should be `src/pages/templates/forms/multistep/basic3StepForm.tsx`

2022-10-23 08:31 UTC, Prasanna0908 commented
Hey, @hauptrolle I made the required change. Can you please check once?

2022-10-23 08:44 UTC, hauptrolle commented
Please read my comment again. You renamed the wrong file 😬

2022-10-23 08:47 UTC, Prasanna0908 commented
> Please read my comment again. You renamed the wrong file 😬

Is it possible to join a google meet? It would be convenient

2022-10-23 12:58 UTC, hauptrolle commented
> > Please read my comment again. You renamed the wrong file 😬
> 
> Is it possible to join a google meet? It would be convenient

Nope. Please read my comment. You can test it locally by running `yarn build` and check if the build succeeds.

2022-10-23 15:17 UTC, Prasanna0908 commented
I tried everything as mentioned but it is still giving build error
![image](https://user-images.githubusercontent.com/65851817/197400326-1fb7793b-bf25-4ef6-aa61-b912c32e8b0b.png)

2022-10-23 16:40 UTC, ekhiw commented
@Prasanna0908 i create PR to your fork, maybe i can help

2022-10-23 18:21 UTC, hauptrolle commented
> I tried everything as mentioned but it is still giving build error ![image](https://user-images.githubusercontent.com/65851817/197400326-1fb7793b-bf25-4ef6-aa61-b912c32e8b0b.png)

Have you read the contribution guide? Looks like your Github token is missing ...
https://github.com/hauptrolle/chakra-templates/blob/main/CONTRIBUTING.md

2022-10-24 04:18 UTC, Prasanna0908 commented
Yes, I have provided github token. Also, `yarn build` command is not working on the main branch also. Is it an issue with the previous commit by any chance?

2022-10-24 08:08 UTC, hauptrolle commented
Maybe we should close this PR here, and you create a new one with the file structure I mentioned in my comment earlier?

2022-10-24 08:10 UTC, Prasanna0908 commented
> Maybe we should close this PR here, and you create a new one with the file structure I mentioned in my comment earlier?

I tried that as well. The thing is yarn build is not working on main branch also. Please have a look at it

2022-10-24 08:43 UTC, ekhiw commented
@Prasanna0908 please check my pull request to your fork, im fixing file structure and typo.

2022-10-24 09:13 UTC, Prasanna0908 commented
I think all checks have passed now. Now check once @hauptrolle . Thanks @ekhiw

2022-10-26 06:30 UTC, hauptrolle approved these changes

2022-10-26 06:30 UTC, merged