Feature/update nextjs13
hauptrolle/chakra-templates pull request #288
Opened 2023-07-08 18:48 UTC by luas10c

### Features
* add support nextjs13
* add eslint
* add prettier
* add commitlint
* add sharp resize image in production mode
* update framer-motion
* update @chakra-ui/react
* update @chakra-ui/icons
* update husky v8
* add lint-staged
* add husky hooks commit-msg, pre-commit and pre-push
* fix more bugs
* fix layout shift caused by fonts

2023-07-09 12:28 UTC, fernandounger commented
nice PR🎉
I was waiting for this nextjs update

2023-07-11 21:45 UTC, fpdsjr commented
Wow insane job, you should be proud of this work gj!

2023-07-12 19:10 UTC, hauptrolle commented
@luas10c Nice! I will try to take a look at this this week!

2023-07-14 15:00 UTC, hauptrolle requested changes
What a PR 🙈 Looks good so far, just some small config changes.

2023-07-16 22:40 UTC, luas10c commented on .prettierrc.js
> +  jsxBracketSameLine: true,
this two?

singleQuote: true,
jsxBracketSameLine: true,

2023-07-16 22:55 UTC, luas10c commented on .prettierrc.js
> +  jsxBracketSameLine: true,
I didn't change that, it's like the original, just compare.

2023-07-16 23:27 UTC, luas10c commented
@hauptrolle 

```js
// .eslintrc.js

/** @type{import('prettier').Config} */
module.exports = {
  tabWidth: 2,
  useTabs: false,
  singleQuote: true,
  jsxBracketSameLine: true,
  bracketSpacing: true,
  trailingComma: 'all',
  arrowParens: 'always',
  singleAttributePerLine: false,
  endOfLine: 'lf',
  bracketSameLine: true,
  printWidth: 90,
  semi: false,
  plugins: []
}
```

Also removed this on body:
<body cz-shortcut-listen="true">

This was from an extension called colorzilla

2023-07-24 13:54 UTC, merged

2023-07-24 13:54 UTC, hauptrolle commented
Merged!