proposal: Social Media OAuth Buttons
hauptrolle/chakra-templates pull request #59
Opened 2021-02-22 13:33 UTC by MichaelGrigoryan25

- Added Social Media OAuth Buttons
- Updated the dependencies

2021-02-22 13:42 UTC, hauptrolle requested changes
Looking good so far 👍 

Just one small change. Can you add some padding to the single button examples?
Otherwise it is a little bit to close to the iframe container => https://chakra-templates-git-fork-michaelgrigoryan25-main-hauptrolle.vercel.app/components/social-media-buttons#Messenger

2021-02-22 13:43 UTC, MichaelGrigoryan25 commented
> Looking good so far 👍
> 
> Just one small change. Can you add some padding to the single button examples?
> Otherwise it is a little bit to close to the iframe container => https://chakra-templates-git-fork-michaelgrigoryan25-main-hauptrolle.vercel.app/components/social-media-buttons#Messenger

Sure. That's what I have been thinking too so far... will do 👍

2021-02-22 13:56 UTC, hauptrolle approved these changes

2021-02-22 13:58 UTC, merged

2021-03-08 11:54 UTC, hauptrolle commented
@all-contributors please add @MichaelGrigoryan25  for code