Add blog basics
hauptrolle/chakra-templates pull request #67
Opened 2021-04-06 20:51 UTC by igeligel

That should add to the blog article list. Will add a blog at some point in another Pull Request.

![localhost_3000_blog_blog-article-list (1)](https://user-images.githubusercontent.com/12736734/113776653-6abb1c00-972a-11eb-836b-610f3634929f.png)

![localhost_3000_blog_blog-article-list (2)](https://user-images.githubusercontent.com/12736734/113776662-6e4ea300-972a-11eb-8d59-c794ccbd57a1.png)

Color schema is changeable. I can change it now if you want but I am fine with it. Works on mobile as well. 

Otherwise, I added a new section called blog since I think it belongs there. If you want to make any change, feel free to reach out to me.

2021-04-06 20:51 UTC, igeligel commented
Should handle #62

2021-04-07 15:18 UTC, hauptrolle requested changes
Overall a nice template. I just have minor adjustments. After that I can merge and release it 👍 

Thank you so much for that addition!

2021-04-07 15:18 UTC, hauptrolle commented on src/pages/templates/blog/blog-article-list/articleList.tsx
> +    <Box marginTop="2" display="flex" alignItems="center">
You can probably use the `Stack` component here and define `space={2}` to avoid to add `marginLeft="2"` to all childs.

2021-04-07 15:18 UTC, hauptrolle commented on src/pages/templates/blog/blog-article-list/articleList.tsx
> +        marginTop={['1', '5']}
I like the object syntax for responsive styles a little bit better: https://chakra-ui.com/docs/features/responsive-styles#the-object-syntax

2021-04-07 15:18 UTC, hauptrolle commented on src/pages/templates/blog/blog-article-list/articleList.tsx
> +              bgGradient={useColorModeValue(
Super cool to use a gradient for that background! 👍

2021-04-07 15:18 UTC, hauptrolle commented on src/pages/templates/blog/blog-article-list/articleList.tsx
> +      <Box paddingTop="40px">
Same here. Just use a `Stack` to avoid the multiple `marginTop's`

2021-04-07 17:31 UTC, igeligel commented
Hey @hauptrolle Fixed all the issues. Feel free to merge if you are fine with the code :)

2021-04-08 06:28 UTC, hauptrolle approved these changes
Looking good!

2021-04-08 06:28 UTC, merged

2021-04-08 06:32 UTC, hauptrolle commented
@all-contributors please add @igeligel  for code